### PR TITLE
Fix osx-arm64 cross build.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by isuruf — CHANGES_REQUESTED** [review]
We need to fix perl pinning. See https://github.com/conda-forge/perl-feedstock/issues/48#issuecomment-732273840

**Comment by erykoff** [comment]
@isuruf So I'm not sure what the action item is ... do I need to wait for that issue to close?

**Comment by isuruf** [comment]
cc @mbargull

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by erykoff** [comment]
@isuruf I rerendered on the command line and pushed.  Still no idea why bot rerenders don't work with my PRs.

**Comment by isuruf** [comment]
@erykoff, since I couldn't push to your branch, I pushed your changes to https://github.com/conda-forge/texinfo-feedstock/pull/18

**Comment by erykoff** [comment]
@isuruf Ah!  I should close this PR then?

**Comment by isuruf** [comment]
Yes

**Pull request closed without merging**
